<a href="https://colab.research.google.com/github/yewlienn-2025/data_science_toolkit/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Tutorial** **3**

In [1]:
import numpy as np

1. Create a numpy array of size 2 x 2

In [13]:
n1=np.array(([2,2],[3,4]))
print(n1)

[[2 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [15]:
n2=np.random.random((3,4))
print(n2)

[[0.39553189 0.75055692 0.9218756  0.35248929]
 [0.77544531 0.87563151 0.53752569 0.44604243]
 [0.07664102 0.35705467 0.30778589 0.47211411]]


3. Create a numpy array of ones and a numpy array of zeroes

In [17]:
n3=np.ones((2,2))
n4=np.zeros((2,2))
print(n3)
print(n4)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [19]:
num4=np.random.random((6,3))
print(num4)

[[0.20849066 0.24563677 0.41114113]
 [0.60702187 0.81675866 0.89226123]
 [0.82125696 0.742098   0.37192316]
 [0.72268187 0.42452204 0.04274521]
 [0.62316197 0.69589766 0.64696477]
 [0.95468712 0.505573   0.34333856]]


In [26]:
#Transpose
num4 =np.transpose(num4)
print(num4)

[[0.20849066 0.60702187 0.82125696 0.72268187 0.62316197 0.95468712]
 [0.24563677 0.81675866 0.742098   0.42452204 0.69589766 0.505573  ]
 [0.41114113 0.89226123 0.37192316 0.04274521 0.64696477 0.34333856]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [30]:
n=1
p=4
m=3
num5=np.random.random((n,p))
num6=np.random.random((p,m))

A=np.dot(num5,num6)

print("Array 1:\n", num5)
print("\nArray 2:\n", num6)
print("\nDot product:\n", A)

Array 1:
 [[0.1565661  0.78224036 0.67164915 0.79452784]]

Array 2:
 [[0.4659398  0.99247201 0.66946365]
 [0.75330387 0.75617776 0.82998284]
 [0.53195985 0.48579704 0.14803517]
 [0.99444986 0.91324505 0.2269359 ]]

Dot product:
 [[1.80962356 1.79878402 1.03379597]]
